import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings('ignore')
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

def run_truth_check():
    # Gauge Inversion Fixes
    file_path = "archive/fractal_manifold_6M.parquet"
    print("[*] AION TRUTH CHECK: Verifying the GBPJPY Laplacian Thesis...")
    
    try:
        df = pd.read_parquet(file_path)
    except Exception as e:
        print(f"[!] Error: {e}")
        return

    # Lock onto the exact T=0 coordinate generated by the Insight Engine
    rupture_time = pd.to_datetime("2026-02-23 01:59:00")
    
    post_rupture_df = df[df.index >= rupture_time].copy()
    
    if post_rupture_df.empty:
        print("[-] Fatal: No forward data available.")
        return

    print(f"[*] Locking Ground Truth (T=0) at {rupture_time}...")
    
    puller = "USDJPY"
    trap_outlet = "GBPJPY"
    direction = "UPWARD"
    
    # Walk forward exactly 50,000 physical network transactions (Eradicating human time)
    vol_cols = [c for c in post_rupture_df.columns if c.endswith('_M1_vol')]
    post_rupture_df['post_energy'] = post_rupture_df[vol_cols].sum(axis=1).cumsum()
    forward_df = post_rupture_df[post_rupture_df['post_energy'] <= 50000]

    if forward_df.empty:
        print("[-] Fatal: Not enough energy in forward stream.")
        return
        
    p0_trap = forward_df[f"{trap_outlet}_M1_price"].iloc[0]
    
    print("[*] Tracking Kinetic Catch-Up and Regression...")
    
    # Calculate pure physical displacement (Prices are already log-transformed in parquet)
    forward_df['Trap_Disp'] = (forward_df[f"{trap_outlet}_M1_price"] - p0_trap) * 100
    
    # The Insight Engine declared a violent UPWARD catch-up for GBPJPY
    max_trap_release = forward_df['Trap_Disp'].max() 
    max_adverse_friction = forward_df['Trap_Disp'].min() 
    
    climax_idx = forward_df['Trap_Disp'].idxmax()
    climax_time = climax_idx.strftime('%Y-%m-%d %H:%M:%S')

    print("\n" + "="*80)
    print("AION ENGINE: POST-RUPTURE TRUTH CHECK")
    print("="*80)
    
    print(f"RUPTURE T=0: {rupture_time}")
    print(f"Forward Track: 50,000 subsequent network transactions.\n")
    
    print(f"[ THE KINETIC DAM ({trap_outlet}) ]")
    print(f"AION Insight Directive: EXPECT {direction} CATCH-UP.")
    
    # The Physics logic
    if direction == "UPWARD":
        release = max_trap_release
        friction = abs(max_adverse_friction)
    else:
        release = abs(max_adverse_friction)
        friction = max_trap_release
        
    print(f"Adverse Friction (Retail Resistance): {friction:+.4f}%")
    print(f"Maximum Kinetic Release (The Dam Break): {release:+.4f}%")
    
    print("\n[ POST-RUPTURE AUTOPSY ]")
    
    # If the upward snap is > 2x the downward friction, the physics hold.
    if release > (friction * 2) and release > 0.02:
        print(f"STATUS: FALSIFICATION PASSED. THE DOCTRINE HOLDS.")
        print(f"-> At T=0, {trap_outlet} was absorbing the wave and flashing negative velocity.")
        print(f"-> The Graph Laplacian accurately mapped the diffusion of energy.")
        print(f"-> The Dam broke. The node experienced a violent {release:+.4f}% release at {climax_time}.")
    else:
        print(f"STATUS: FALSIFICATION FAILED. THE DAM HELD.")
        print(f"-> The energy failed to diffuse through the network.")
        
    print("="*80)

if __name__ == "__main__":
    run_truth_check()
