import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings('ignore')
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

def run_outcome_memory():
    file_path = "archive/fractal_manifold_6M.parquet"
    print(f"[*] AION OUTCOME MEMORY: Loading Fractal Tensor from {file_path}")
    
    try:
        df = pd.read_parquet(file_path)
    except Exception as e:
        print(f"[!] Critical Error: Data missing. {e}")
        return

    # Lock onto the exact T=0 coordinate generated by the Observatory
    rupture_time = pd.to_datetime("2026-03-23 21:10:00")
    
    # Isolate the forward-time manifold
    post_rupture_df = df[df.index >= rupture_time].copy()
    
    if post_rupture_df.empty:
        print("[-] Fatal: No forward data available after rupture point.")
        return

    print(f"[*] Locking Ground Truth (T=0) at {rupture_time}...")
    
    epicenter = "AUDUSD"
    trap_outlet = "EURUSD"
    
    # We walk forward exactly 100,000 physical network transactions (Eradicating human time)
    vol_cols = [c for c in post_rupture_df.columns if c.endswith('_M1_vol')]
    post_rupture_df['post_energy'] = post_rupture_df[vol_cols].sum(axis=1).cumsum()
    forward_df = post_rupture_df[post_rupture_df['post_energy'] <= 100000]

    if forward_df.empty:
        print("[-] Fatal: Not enough energy in forward stream.")
        return
        
    # Baseline Raw Closes at T=0
    p0_epi = forward_df[f"{epicenter}_M1_price"].iloc[0]
    p0_trap = forward_df[f"{trap_outlet}_M1_price"].iloc[0]
    
    print("[*] Tracking Kinetic Extension and Forced Liquidation...")
    
    # Calculate pure physical displacement (log returns from T=0)
    # Gauge Inversion Fix: The tensor is ALREADY log(price). 
    # Therefore, log(Pt/P0) is mathematically equal to (log(Pt) - log(P0)).
    forward_df['Epi_Displacement'] = (forward_df[f"{epicenter}_M1_price"] - p0_epi) * 100
    forward_df['Trap_Displacement'] = (forward_df[f"{trap_outlet}_M1_price"] - p0_trap) * 100
    
    # We want to see the path of the Trap over the energy window
    # Arbiter commanded SHORT (SELL).
    # Adverse Friction = Max Extension (price going up against us)
    # Kinetic Release = Max Drawdown (price dumping in our favor)
    
    max_trap_extension = forward_df['Trap_Displacement'].max() 
    max_trap_liquidation = forward_df['Trap_Displacement'].min() 
    
    # Find the exact timestamp the Trap sprang (Maximum kinetic release downward)
    climax_idx = forward_df['Trap_Displacement'].idxmin()
    climax_time = climax_idx.strftime('%Y-%m-%d %H:%M:%S')
    
    # What was the Epicenter doing during this?
    epi_at_climax = forward_df.loc[climax_idx, 'Epi_Displacement']

    print("\n" + "="*80)
    print("AION ENGINE: POST-RUPTURE FALSIFICATION REPORT")
    print("="*80)
    
    print(f"RUPTURE T=0: {rupture_time}")
    print(f"Forward Track: 100,000 subsequent network transactions.\n")
    
    print(f"[ THE EPICENTER ({epicenter}) - The Anchor ]")
    print(f"Displacement at Liquidation Climax: {epi_at_climax:+.4f}%")
    
    print(f"\n[ THE WEAKEST OUTLET ({trap_outlet}) - The Forced Physics ]")
    print(f"AION Arbiter Directive: SHORT (SELL) the M1 Retail Trap.")
    print(f"Adverse Friction (Fake Retail Pump): {max_trap_extension:+.4f}%")
    print(f"Maximum Kinetic Release (The Crash): {max_trap_liquidation:+.4f}%")
    
    print("\n[ POST-RUPTURE AUTOPSY ]")
    
    # Falsification logic: The crash must heavily outweigh the fake pump.
    if abs(max_trap_liquidation) > (max_trap_extension * 2):
        print(f"STATUS: FALSIFICATION PASSED. THE DOCTRINE HOLDS.")
        print(f"-> At T=0, {trap_outlet} was flashing fake positive velocity (The Trap).")
        print(f"-> The true Meso pressure wave forced its way through {trap_outlet}.")
        print(f"-> The Outlet experienced a violent {max_trap_liquidation:+.4f}% forced liquidation at {climax_time}.")
    else:
        print(f"STATUS: FALSIFICATION FAILED. THE TRAP HELD.")
        print(f"-> The pressure wave did not force liquidation through the expected outlet.")
        
    print("="*80)

if __name__ == "__main__":
    run_outcome_memory()
